.TH git-graphviz 1 2018-05-20 "WRTools: Git"
.SH NAME
git-graphviz \- Graphical vizualization of Git repositories via Graphviz
.SH SYNOPSIS
.B git-graphviz
[
.I options
]
.B --
[
.I rev-list
]
.SH DESCRIPTION
\*(lqgit-graphviz\*(rq generates a graph of a Git repository, using the Graphviz
graph generation application.
